export const config = {
  appId: import.meta.env.VITE_REACT_appId,
  appUrl: import.meta.env.VITE_REACT_appUrl,
  baseUrl: import.meta.env.VITE_REACT_baseUrl,
  clientApiBaseUrl: import.meta.env.VITE_REACT_clientApiBaseUrl,
  dataApiBaseUrl: import.meta.env.VITE_REACT_dataApiBaseUrl,
  dataExplorerLink: import.meta.env.VITE_REACT_dataExplorerLink,
  dataSourceName: import.meta.env.VITE_REACT_dataSourceName,
  projectId: import.meta.env.VITE_REACT_projectId,
  githubUsername: import.meta.env.VITE_REACT_githubUsername,
  githubToken: import.meta.env.VITE_REACT_githubToken,
  pkUploadcare: import.meta.env.VITE_REACT_pkUploadcare,
  skUploadcare: import.meta.env.VITE_REACT_skUploadcare,
  openaiOrg: import.meta.env.VITE_REACT_openaiOrg,
  loopsKey: import.meta.env.VITE_REACT_loopsKey,
  openaiKey: import.meta.env.VITE_REACT_openaiKey,
  cpanelUsername: import.meta.env.VITE_REACT_cpanelUsername,
  cpanelPassword: import.meta.env.VITE_REACT_cpanelPassword,
  stripePk: import.meta.env.VITE_REACT_stripePk,
  stripeProPlanPriceId: import.meta.env.VITE_REACT_stripeProPlanPriceId,
};
